# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: al3xtig3r.portfolio::lang.customers.single

# Model Form Field configuration
form: $/al3xtig3r/portfolio/models/customer/fields.yaml

# Model Class name
modelClass: Al3xTig3r\Portfolio\Models\Customer

# Default redirect location
defaultRedirect: al3xtig3r/portfolio/customers

# Create page
create:
    title: al3xtig3r.portfolio::lang.customers.create.title
    redirect: al3xtig3r/portfolio/customers/update/:id
    redirectClose: al3xtig3r/portfolio/customers

# Update page
update:
    title: al3xtig3r.portfolio::lang.customers.update.title
    redirect: al3xtig3r/portfolio/customers
    redirectClose: al3xtig3r/portfolio/customers

# Preview page
preview:
    title: al3xtig3r.portfolio::lang.customers.preview.title
